{"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"metadata":{"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","role":"symbol","roleHeading":"Case","title":"IdVerificationError.clientError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"IdVerification365id"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","role":"symbol","title":"IdVerificationError.clientError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","title":"IdVerification365id","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerror","type":"topic","title":"IdVerificationError","role":"symbol","navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"}}}