{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case","role":"symbol","modules":[{"name":"IdVerification365id"}],"title":"IdVerificationError.clientError","roleHeading":"Case"},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationError"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"code":"onError(error:)","type":"codeVoice"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","role":"collection","title":"IdVerification365id","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","role":"symbol","title":"IdVerificationError.clientError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"kind":"symbol"}}}