{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"metadata":{"modules":[{"name":"IdVerification365id"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"title":"IdVerificationError.clientError","role":"symbol","roleHeading":"Case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","title":"IdVerificationError.clientError","kind":"symbol","role":"symbol","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"type":"text","text":" method in the "},{"code":"IdVerificationEventDelegate","type":"codeVoice"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","role":"symbol","type":"topic","title":"IdVerificationError","navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerror"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","type":"topic","title":"IdVerification365id","url":"\/documentation\/idverification365id"}}}