{"kind":"symbol","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"metadata":{"modules":[{"name":"IdVerification365id"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"roleHeading":"Case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","title":"IdVerificationError.clientError","role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","title":"IdVerification365id","role":"collection","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","title":"IdVerificationError.clientError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","role":"symbol","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","url":"\/documentation\/idverification365id\/idverificationerror","kind":"symbol","title":"IdVerificationError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"type":"topic"}}}