{"sections":[],"abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"IdVerification365id"}],"symbolKind":"case","role":"symbol","title":"IdVerificationError.serverError","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverError"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"code":"onError(error:)","type":"codeVoice"},{"type":"text","text":" method in the "},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"type":"topic","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/servererror","title":"IdVerificationError.serverError","abstract":[{"text":"Happens when there is an error thrown by the 365id server","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverError"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"}}}