{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"metadata":{"title":"IdVerificationError.serverError","modules":[{"name":"IdVerification365id"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Happens when there is an error thrown by the 365id server","type":"text"}],"variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/servererror","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"title":"IdVerificationError.serverError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"url":"\/documentation\/idverification365id\/idverificationerror","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}]}}}