{"sections":[],"abstract":[{"text":"Happens when there is an error thrown by the 365id server","type":"text"}],"metadata":{"roleHeading":"Case","title":"IdVerificationError.serverError","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"IdVerification365id"}]},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationError"}],"role":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","title":"IdVerificationError.serverError","url":"\/documentation\/idverification365id\/idverificationerror\/servererror","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"url":"\/documentation\/idverification365id","title":"IdVerification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","type":"topic","role":"collection"}}}