{"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"IdVerificationError.serverError","roleHeading":"Case","symbolKind":"case","modules":[{"name":"IdVerification365id"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"role":"collection","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationError"}],"navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"type":"text","text":" method in the "},{"type":"codeVoice","code":"IdVerificationEventDelegate"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/servererror","title":"IdVerificationError.serverError","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"}}}