{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"metadata":{"title":"onError(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","modules":[{"name":"IdVerification365id"}],"symbolKind":"method","required":true},"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate","title":"IdVerificationEventDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationEventDelegate"}],"role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","required":true,"title":"onError(_:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"kind":"symbol","title":"IdVerification365id","role":"collection","type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"title":"IdVerificationErrorBundle","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","type":"topic","role":"symbol","abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerrorbundle","navigatorTitle":[{"text":"IdVerificationErrorBundle","kind":"identifier"}]}}}