{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","modules":[{"name":"IdVerification365id"}],"symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"text":")","kind":"text"}],"title":"onError(_:)","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"url":"\/documentation\/idverification365id\/idverificationeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"IdVerification SDK event Delegate that is informing about various events"}],"title":"IdVerificationEventDelegate","role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"title":"IdVerificationErrorBundle","kind":"symbol","type":"topic","abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"navigatorTitle":[{"text":"IdVerificationErrorBundle","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerrorbundle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationErrorBundle"}],"role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","role":"symbol","type":"topic","kind":"symbol","required":true,"title":"onError(_:)"}}}