{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"recieved."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"IdVerification365id"}],"title":"onError(_:)","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","required":true,"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier","text":"IdVerificationErrorBundle"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"type":"text","text":"recieved."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onError(_:)","required":true,"role":"symbol","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","abstract":[],"kind":"symbol","title":"IdVerification365id","type":"topic","url":"\/documentation\/idverification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","url":"\/documentation\/idverification365id\/idverificationeventdelegate","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"title":"IdVerificationEventDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationEventDelegate"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerrorbundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationErrorBundle"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"title":"IdVerificationErrorBundle","type":"topic","abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}]}}}