{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"sections":[],"metadata":{"role":"symbol","title":"onError(_:)","required":true,"externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"kind":"text","text":")"}],"modules":[{"name":"IdVerification365id"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"type":"text","text":"recieved."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","url":"\/documentation\/idverification365id\/idverificationerrorbundle","role":"symbol","type":"topic","abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"title":"IdVerificationErrorBundle","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationEventDelegate"}],"title":"IdVerificationEventDelegate","navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"role":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate","type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"url":"\/documentation\/idverification365id","title":"IdVerification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","type":"topic","role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"role":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","required":true,"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"onError(_:)","kind":"symbol"}}}